layer.conf: Remove unused line
Remove unused variable that is looking for custom-licenses folder within the
layer. Since the custome-licenses folder doesnt exist, bitbake parse fails with
the following error:
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (bitbake-cookerdaemon.log):
--- Starting bitbake server pid 13584 at 2020-06-09 18:37:42.833172 ---
ERROR: Unable to parse Var <AVAILABLE_LICENSES[:=]>
Traceback (most recent call last):
  File "Var <AVAILABLE_LICENSES[:=]>", line 1, in <module>
  File "core/meta/classes/license.bbclass", line 275, in
available_licenses(d=<bb.data_smart.DataSmart object at 0x7f867e50bac8>):
         for lic_dir in lic_dirs:
    >        licenses += os.listdir(lic_dir)

bb.data_smart.ExpansionError: Failure expanding variable
AVAILABLE_LICENSES[:=], expression was ${@' '.join(available_licenses(d))}
which triggered exception FileNotFoundError: [Errno 2] No such file or
directory: 'core/../meta-openamp/files/custom-licenses'

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>