open-amp-xlnx.inc: Remove plnx-deploy bbclass
Building SDT images using core-image-full-cmdline target fails to parse
errors.

ERROR: ParseError at /scratch/sandeep/yocto/2024.1/yp-bc/sources/meta-openamp/vendor/xilinx/meta-xilinx-standalone-experimental/recipes-openamp/open-amp/open-amp-xlnx.inc:5: Could not inherit file classes/plnx-deploy.bbclass
ERROR: Parsing halted due to errors, see error messages above

Hence remove plnx-deploy bbclass as this bbclass should be inherited
only when meta-petalinux layer is included.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>