libmetal: Workaround for atomic setting
Workaround for:

libmetal-v2024.05+git/test/system/linux/atomic.c:31:30: error: implicit declaration of function 'ATOMIC_VAR_INIT'; did you mean 'ATOMIC_FLAG_INIT'? [-Wimplicit-function-declaration]
|    31 |         atomic_int counter = ATOMIC_VAR_INIT(0);
|       |                              ^~~~~~~~~~~~~~~
|       |                              ATOMIC_FLAG_INIT

ATOMIC_VAR_INIT is obsolete now and no longer is C23 or newer.

This wouldaround should be removed once the source is resolved.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>